### ISSUE TITLE
dependabot/pip/tensorflow-1.15.2 分支运行报错

### ISSUE THREAD

**Issue by lyjbupt** [guanshuicheng/invoice#19]
1.15.2 这个版本支持吗？

Traceback (most recent call last):
  File "app.py", line 14, in <module>
    from model_post_type import ocr as OCR
  File "/home/test/invoice/model_post_type.py", line 32, in <module>
    from text import keras_detect_type as detect
  File "/home/test/invoice/text/keras_detect_type.py", line 23, in <module>
    box_score = box_layer([*textModel.output,image_shape,input_shape],anchors, num_classes)
  File "/home/test/invoice/text/keras_yolo3.py", line 366, in box_layer
    boxes  = concatenate(boxes, axis=0)
  File "/test/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/merge.py", line 705, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/test/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 802, in __call__
    base_layer_utils.create_keras_history(inputs)
  File "/test/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 184, in create_keras_history
    _, created_layers = _create_keras_history_helper(tensors, set(), [])
  File "/test/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 231, in _create_keras_history_helper
    layer_inputs, processed_ops, created_layers)
  File "/test/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 231, in _create_keras_history_helper
    layer_inputs, processed_ops, created_layers)
  File "/test/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 231, in _create_keras_history_helper
    layer_inputs, processed_ops, created_layers)
  [Previous line repeated 2 more times]
  File "/test/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py", line 229, in _create_keras_history_helper
    constants[i] = backend.function([], op_input)([])
  File "/test/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "/test/anaconda3/envs/py37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_367' with dtype float and shape [2]
         [[{{node Placeholder_367}}]]

**Comment by lyjbupt** [comment]
change to use old version, the app can start now.
