### ISSUE TITLE
AttributeError: module 'tensorflow_core.keras.backend' has no attribute 'get_session'

### ISSUE THREAD

**Issue by tommyxiang** [guanshuicheng/invoice#49]
I got the error like this :

Traceback (most recent call last):
  File "app.py", line 14, in <module>
    from model_post_type import ocr as OCR
  File "/Users/xianglingyun/invoice_ocr/invoice-master/model_post_type.py", line 32, in <module>
    from text import keras_detect_type as detect
  File "/Users/xianglingyun/invoice_ocr/invoice-master/text/keras_detect_type.py", line 19, in <module>
    sess = K.get_session()

can you tell me how to fix it?

**Comment by Sai1978** [comment]
you version is too higer
